# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# Site settings
locale                   : "en"
title                    : "PIKAROOT ▌"
title_separator          : "|"
name                     : "pikaroot"
description              : "Yet another site but in Pokémon Theme for cyber security enthusiasts to visit."
repository               : "pikaroot/pikaroot.github.io"
url                      : "https://pikaroot.github.io"
baseurl                  : # the subpath of your site, e.g. /blog
words_per_minute         : 120
twitter_username         : "p1karoot"
github_username          : "pikaroot"

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

permalink      : /:collection/:categories/:title
paginate       : 8
paginate_path  : /page:num/
timezone       : Asia/Singapore

# search: true

breadcrumbs: true

# Build settings
markdown: kramdown

collections:
  ctfs:
    output: true
    # permalink: /:collection/:categories/:title
  blogs:
    output: true
    # permalink: /:collection/:path
  about:
    output: true
    # permalink: /:collection/:path

category_archive:
  type: jekyll-archives
  path: /ctfs/
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive-taxonomy
  permalinks:
    category: /:categories/

# Default Front Matter
defaults:
  # _posts
  - scope:
      path            : ""
      type            : posts
    values:
      layout          : single
      classes         : wide
      author_profile  : true
      read_time       : true
      show_date       : true
      related         : false
  - scope:
      path            : ""
    values:
      sidebar:
        nav           : "docs"
  # _pages
  - scope:
      path            : ""
      type            : pages
    values:
      layout          : category
      author_profile  : true
  # _blogs
  - scope:
      path            : ""
      type            : blogs
    values:
      layout          : single
      classes         : wide
      author_profile  : true
      read_time       : true
      show_date       : true
      related         : false

# Site Author
author:
  name              : "david lim"
  avatar            : "/assets/images/dp-fuecoco.JPG"
  bio               : "A typical Pokémon fan."
  email             : "asterlwx2001@gmail.com"
  links:
    - label  : "Twitter"
      icon   : "fab fa-fw fa-twitter-square"
      url    : "https://twitter.com/p1karoot"
    - label  : "GitHub"
      icon   : "fab fa-fw fa-github"
      url    : "https://github.com/pikaroot"
    - label  : "LinkedIn"
      icon   : "fab fa-fw fa-linkedin-in"
      url    : "https://www.linkedin.com/in/limweixun/"

atom_feed:
  hide: true

# Includes
include: 
  - _pages
  - _blogs

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
